services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: infra-sql_server
    ports:
      - "${PORT}:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
    volumes:
      - infra-sql_server-data:/var/opt/mssql
    networks:
      - df-network
    labels:
      managed-by: docker-framework
      df.type: infra
      df.resource: sql_server
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -C -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  infra-sql_server-data:
    name: infra-sql_server-data

networks:
  df-network:
    name: df-network
    external: true
